var about_ht = "<h1>Welcome to Leland's Mind Map</h1> <p>Click on any of the icons in the brain to explore!</p><p>You'll find pictures and descriptions of the different aspects of my life as well as links to content and projects I've produced.</p><img src='images/sixthcollege.jpg' class='resp centered'><p>This website was originally completed as a Digital Media Storytelling Project for CAT 125. As a computer science major, I've kept myself almost exclusively involved with backend development. I have never delved very far into website design. The challenge here was building this website from scratch, writing each line of HTML/CSS/Javascript/jQuery myself.</p>";

var resources_ht = '<h1>Resources</h1><p>&#149;"jQuery Tutorial." <i>w3schools</i>. Refsnes Data, n.d. Web. 6 Dec. 2015.</p><p>&#149;"Javascript Tutorial." <i>w3schools</i>. Refsnes Data, n.d. Web. 6 Dec. 2015.</p><p>&#149;"HTML Tutorial." <i>w3swas chools</i>. Refsnes Data, n.d. Web. 6 Dec. 2015.</p><p>&#149;"CSS Tutorial." <i>w3schools</i>. Refsnes Data, n.d. Web. 6 Dec. 2015.</p><p>&#149;"Brain Activity&#8212;Metacognition." <i>Openclipart</i>. N.p., n.d. Web. 06 Dec. 2015.</p>';

var workexp_ht = "<h1>Work Experience</h1><p><a href='https://www.dropbox.com/s/t4vkt1z7v874mo7/Resume_LelandTran_2015.pdf?dl=0'>Resume (PDF)</a></p><p>&#149;Graduating Senior at UCSD with in Computer Science (BS).</p><p>&#149;Former intern at Visa and Teradata.</p><p>&#149;Experienced in REST and Object-Oriented Programming.</p><p>I'm passionate about efficient software design, sharing ideas, and continuous self-improvement. I'm looking to surround myself with colleagues that truly enjoy what they are working on and to add to that a knack for problem-solving, an unrelenting smile, and a vaguely above average amount of charisma&#8212;at least I'd like to think so.</p><h1>Past Projects</h1><p>&#149;<a href='http://gradewish.herokuapp.com/login'>Gradewish</a>: A tool created to help students track their grades and help them achieve their dreams (in the context of their school transcript).</p><p>&#149;<a href='http://splurge.herokuapp.com/'>Splurge</a>: A restaurant management application that allows restaurants to take delivery and carryout orders from the Splurge Android app users as well as display their menu, location, and hours.</p><p>&#149;<a href='https://www.youtube.com/watch?v=4kkwm3R8iOQ'>Lazy Econ</a>: An AP Microeconomics video (17k views). My proudest achievement, in fact. This video was the product of my team management skills and ability to execute and it was done with my best friends.</p>";

var family_ht = "<h1>Family and Friends</h1><p>The most important aspect of my life is my family. My parents, sister, and cousins have always been so supportive with unconditional love. Having gone through the meager hardships of immigration, my parents have come a long way to provide my sister and me with a comfortable and successful life. Every day, I work to hard realize their dreams and aspirations.</p><img src='images/family.jpeg' class='resp centered'><p>As for my friends, I could not ask for better. I'm not sure what I've done exactly to have met such an extraordinary set of people that are so caring, considerate, and genuine.</p>";

var tke_ht = "<h1>Tau Kappa Epsilon Fraternity</h1><p>Joining TKE was a decision I made in the Spring quarter of my junior year. Although I loved the people that were in my life at the time, especially the ones that continue to play an active role in my life today, I still thirsted to build a stronger and wider network of peers. During pledging, I realized the gravity of TKE's brotherhood and I felt extremely privileged to be joining something so genuine and resolute. TKE showed me the value of true loyalty and I have since gained over a hundred brothers that I can rely on and that can rely on me.</p> <p>TKE, I love this fraternity.</p><img src='images/tkefa15.jpg' class='resp centered'>";

var smash_ht = "<h1>Super Smash Bros. Melee</h1><p>Growing up, I was always a fan of the Super Smash Bros. video game series, but I was never exceptional at them among my group of friends, despite owning Super Smash Bros. Melee for the Nintendo Gamecube. I stopped playing it shortly after leaving middle school.</p><img src='images/ssbmlogo.png' width=50% class='resp centered'><p>However, in my senior year of high school, my friends started playing Melee again, even though the newer version, Super Smash Bros. Brawl, had been out for the Nintendo Wii for a few years. When I started to wonder why, my friends showed me just how technical and elegant gameplay for Melee was. I became obsessed. I started practicing for hours, entering tournaments, and watching video streams online in the hopes of improving. Melee has significantly impacted how I view good design, in video games and in user experience. It's a game I don't think I'll ever stop appreciating.</p>";

var photo_ht = "<h1>Photography</h1><p>Photography has been a long time passion of mine. It gives us the ability to record fleeting moments, evoke strong emotions, and shape our beliefs. Personally, I enjoy photos like they're paintings&#8212;beautiful images that astonish the human mind.</p><img src='images/vis60samp.jpg' class='resp centered'><p>View some of my work <a href='https://500px.com/lelandtran'>here</a></p>";

