var about_ht = "<h1>Welcome to Leland's Mind Map</h1> <p>Click on any of the icons in the brain to explore!</p> <p>Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around.Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around.Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around.Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around.Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around. Hello and welcome to Leland's mind map. Here is some filler text to see the text wrap around.</p>";

var resources_ht = "<h1>Resources</h1><p>You've clicked on resources</p> <p>w3schools,lvtran,brainimage</p>";

var workexp_ht = "<h1>Work Experience</h1><p><a href='https://www.dropbox.com/s/t4vkt1z7v874mo7/Resume_LelandTran_2015.pdf?dl=0'>Resume (PDF)</a></p><p>&#149;Graduating Senior at UCSD with B.S. in Computer Science.</p><p>&#149;Former intern at Visa and Teradata.</p><p>&#149;Experienced in REST and Object-Oriented Programming.</p><p>I'm passionate about efficient software design, sharing ideas, and continuous self-improvement. I'm looking to surround myself with colleagues that truly enjoy what they are working on and to add to that a knack for problem-solving, an unrelenting smile, and a vaguely above average amount of charisma&#8212;at least I'd like to think so.</p>";

var family_ht = "<h1>Family and Friends</h1><p>The most important aspect of my life is my family. My parents, sister, and cousins have always been so supportive with unconditional love. Having gone through the meager hardships of immigration, my parents have come a long way to provide my sister and me with a comfortable and successful life. Every day, I work to hard realize their dreams and aspirations.</p>";

var tke_ht = "<h1>Tau Kappa Epsilon Fraternity</h1><p>Joining TKE was a decision I made in the Spring quarter of my junior year. Although I loved the people that were in my life at the time and continue to play an active role in my life today, I felt like I could still build a stronger and wider network of peers. During pledging, I realized just how strong TKE's brotherhood was and I felt extremely privileged to be joining something so genuine and resolute. TKE showed me the value of true loyalty and I have since come out with over a hundred brothers that I can rely on and that can rely on me.</p> <p>TKE, I love this fraternity.</p>";

var smash_ht = "<h1>Super Smash Bros. Melee</h1><p>Growing up, I was always a fan of the Super Smash Bros. video game series, but I was never exceptional at them among my group of friends, despite owning Super Smash Bros. Melee for the Nintendo Gamecube. I stopped playing it shortly after leaving middle school. However, in my senior year of high school, my friends started playing Melee again, even though the newer version, Super Smash Bros. Brawl, had been out for the Nintendo Wii for a few years. When I started to wonder why, my friends showed me just how technical and elegant gameplay for Melee was. I became obsessed. I started practicing for hours, entering tournaments, and watching video streams online in the hopes of improving. Melee has significantly impacted how I view good design, in video games and in user experience. It's a game I don't think I'll ever stop appreciating.</p>";

var photo_ht = "<h1>Photography</h1><p>Photography has been a long time passion of mine. It gives us the ability to record fleeting moments, evoke strong emotions, and shape our beliefs. Personally, I enjoy photos like they're paintings&#8212;beautiful images that astonish the human mind.</p><p>View some of my work <a href='https://500px.com/lelandtran'>here</a></p>";

